### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by maticstric** [bobrk/edna-ferber_so-big#1]
Before starting:

- [x] clean makes changes which should be accepted
- [x] build-images makes changes (I think it's removing some metadata) which should be accepted

Some italics related issues:

- chapter-1.xhtml
  - [x] In line 15 the second "So-o-o-o" shouldn't be emphasized according to the scans
- chapter-3.xhtml
  - [x] `<i>such</i>` -> `<em>such</em>`
  - [x] All the `<span xml:lang="nl">` should be `<i xml:lang="nl">` (https://standardebooks.org/manual/1.6.2/single-page#8.2.9.1). This will bring up a lint issue which you should fix.
- chapter-4.xhtml
  - [x] `<i>Fireside Companion<i>` -> `<i epub:type="se:name.publication.magazine">Fireside Companion<i>`
- chapter-5.xhtml
  - [x] `<i>Fireside Companion<i>` -> `<i epub:type="se:name.publication.magazine">Fireside Companion<i>`
- chapter-6.xhtml
  - [x] For the two instances of "McBride’s Grammar" and one instance of "Duffy’s Arithmetic", only the book title should be italicized. I.e. the name.publication.book semantics should be only on "Grammar" and "Arithmetic" since "McBride" and "Duffy" are presumably just the author (though it seems they're invented).
- chapter-8.xhtml
  - [x] `<span xml:lang="nl">Og</span>` -> `<i xml:lang="nl">Og</i>`
- chapter-13.xhtml
  - [x] `<i>Other valuable educative experience in practical life.</i>` -> `<em>Other valuable educative experience in practical life.</em>` (there are two instances).
- chapter-14.xhtml
  - [x] `<span epub:type="z3998:roman">vi</span>` -> `vi`. This was accidentally done by "se semanticate". It's just an elided "visage".
- chapter-16.xhtml
  - [x] `<i>Tribune</i>` -> `<i epub:type="se:name.publication.newspaper">Tribune</i>`

Some abbr related issues:

- chapter-3.xhtml
  - [x] All `<abbr>`s on line 21 should have "eoc" class, not just the last <abbr>
 

Some em dash related issues:

- [x] #2
- [x] #3
- [x] You should typogrify after you fix this as well.

Some CSS related issues:

- [x] The calling-card class can be removed from the xhtml (chapter-7.xhtml) and the two css selectors can be replaced with: `#chapter-7 blockquote p:first-of-type` and `#chapter-7 blockquote p:last-of-type`Generally, SE always avoids css classes by using clever selectors. You'll only see them in very specific cases where a css selector is too complicated or unreadable.

- [x] In chapter-18.xhtml you can remove the `<b>` tags inside the blockquotes and just include "font-variant: small-caps;" in the CSS selector "#chapter-18 blockquote" that you already have.

- [x] For the calling card in chapter 7 I would use "border: 1px solid;" since the thin border looks nicer. There's also this precedent: https://standardebooks.org/manual/1.6.2/single-page#5.2.1

Some other misc. stuff: 

- [x] #4

- [x] Look at https://standardebooks.org/manual/1.6.2/single-page#7.7.2 for semantics and css for the letter in chapter 8. Specifically the "z3998:salutation" semantics.

- [x] It seems that the more common name for the cover artist is "Gari Melchers" and his full name is "Julius Garibaldi Melchers". So in content.opf you should update his name and "file-as" to the more common one and then add the "full-name" property (https://standardebooks.org/manual/1.6.2/9-metadata#9.13.3 and https://standardebooks.org/manual/1.6.2/9-metadata#9.11.4). Don't forget to update the name of the artist in colophon.xhtml as well.

- [x] The "Remove ligatures" commit should be [Editorial]. Look here for how to rebase if you haven't done it before: http://schacon.github.io/history.html (should be pretty simple). Instead of "HEAD~3" you can put the commit id of the commit *before* the "Remove ligatures" commit.

Some edit suggestions for the long description. I'm really bad at writing the long description so these are just *suggestions*. Plus Alex always proofreads them so he might make some changes anyway:

- Add comma before "although"
- Remove comma after "DeJong"
- There's some tense mixing from present to past. You should probably consolidate that.
- That last paragraph doesn't make sense grammatically. Maybe something like "... confident of the book’s prospects. Nevertheless, it became very popular, won her the Pulitzer Prize in 1925, and was later made into three different motion pictures."

For the `<q>` tags I'll ask in the group again because I personally like your solution but Alex said to just keep the quotes. So it's probably good to double-check.

If you have any other questions please ask!

**Comment by bobrk** [comment]
I've done most of these, with a couple opened to track and further conversation awaiting on the email list.

**Comment by bobrk** [comment]
I decided to make the book match the scans, which requires a lint exception, since the first internal thought has an open double quote leading into another quoted sentence in the same paragraph (according to the scan).

**Comment by maticstric** [comment]
Okay, just a couple more things:


- [x] chapter-3.xhtml: Only the "b" should be in italics, not the em dash. Also, make sure the word joiner is outside the italics.

- [x] chapter-8.xhtml: Remove continued class from within the letter. Instead, that indent is removed with this css according to the Examples at https://standardebooks.org/manual/1.6.2/single-page#7.7:
```
[epub|type~="z3998:salutation"] + p{
	text-indent: 0;
}
```
The continued class is only really used after blockquotes to signify that the paragraph preceding the blockquote and the one after are semantically the same paragraph (https://standardebooks.org/manual/1.6.2/single-page#8.4.2.1).

- [x] local.css: Remove the "border-style: solid;" from the calling card css. It's already solid because of "border: 1px solid;"

- [x] Then run typogrify again

**Comment by bobrk** [comment]
Running typogrify again took away the space between the em dash after the _Woorden b_ and the next sentence. Does that seem correct? The scan has a space...

<img width="418" alt="Screen Shot 2022-01-03 at 20 35 46" src="https://user-images.githubusercontent.com/11545160/148010030-ba8793e4-72e6-4c1a-be97-7fd0b4c6b23e.png">

**Comment by maticstric** [comment]
Generally typography is correct so I'd lean on the side of this change being intentional. But maybe you should check on the google groups just in case.

**Comment by maticstric** [comment]
Just a heads up, when adding the salutation CSS you removed a newline at the end of the file (not really sure how you did that tbh since it should be added automatically by your text editor) so you'll need to run `clean` again.

**Comment by bobrk** [comment]
Ok, I think I got everything. Thanks for your thorough review!

**Comment by maticstric** [comment]
Great, everything looks good.

Thanks for sticking through it!
